### ISSUE TITLE
Explain the signature of Cache.remove

### ISSUE THREAD

**Issue by Tvaroh** [evolution-gaming/scache#37]
Hey, can you explain why the result type is `F` of `F` and how it should be used?

```scala
def remove(key: K): F[F[Option[V]]]
```

**Comment by t3hnar** [comment]
Hi, @Tvaroh  

`F[F[Option[V]]]` such result type gives ability to support case of "loading value" to be removed from cache without waiting until it is loaded

Outer `F[_]` is about removing value from cache, inner `F[Option[V]]` describes process of value being loaded, or maybe it is already loaded, who knows…

I really wanted to make sure that "removal" is not blocked by "heavy" entries, and still want to have ability to get value of removed entry.

**Comment by t3hnar** [comment]
in case you want to just remove value and don't really care about what's was the previous - you can just use it as `.remove(key).void`

**Comment by Tvaroh** [comment]
Does it make sense in case of in-memory cache?

**Comment by t3hnar** [comment]
it depends on how you add elements to the `cache`
* in case of `cache.put(...)` it requires loaded value, so you should not worry about "loading" entries
* in case of `cache.getOrUpdate(...)` - you can pass function for loading, for instance heavy query for loading entry from database, so you want to be sure it does not block removal

**Comment by Tvaroh** [comment]
If the heavy query is running at the moment of deletion, then the value is not in the cache and `F.pure(None)` should be returned as a method result, or am I missing something?

**Comment by t3hnar** [comment]
There is entry in case about "value being loaded" for some key, in order to prevent concurrent "loadings" 

Hence when you call twice in a row `cache.getOrUpdate(key)`, only first one will make a call to database, second one call will be waiting for the same result.

**Comment by Tvaroh** [comment]
It sounds like an implementation detail, from the cache user perspective the value is not in the cache. 🤷‍♂️

**Comment by t3hnar** [comment]
yeah, maybe. we have some projects that heavy relies on this detail :)

**Comment by Tvaroh** [comment]
Maybe it should be
```scala
def remove(key: K): F[Unit]
def getAndRemove(key: K): F[Option[V]]
```
Or something like that.

**Comment by t3hnar** [comment]
yep, you can build that interface in top for simplifications, we also have similar in some places, not open sourced :(

**Comment by drobazko** [comment]
Hi folks.

Could someone to explain the following method:
```
def remove(key: K): F[F[Option[V]]]
```
What could be the actual type for `F` type over here?
Could it be Future?
```def remove(key: K): Future[Future[Option[V]]]```

**Comment by t3hnar** [comment]
Hey @drobazko, it could be the `Future` in scope of `API`, however not that internals could wokr properly if you would parametrise cash during creation with `Future`

**Comment by drobazko** [comment]
Hi @t3hnar.
Thank you very much for the prompt response.
If not Future, but what could it be?

**Comment by t3hnar** [comment]
Most popular are:
* [IO](https://typelevel.org/cats-effect/docs/2.x/datatypes/io) (what we actually use at Evolution)
* [ZIO](https://zio.dev/overview/getting-started)

After obtaining `IO[???]`, you can convert this to `Future`, but you cannot create instance of cache with `Future`, because you won't be able to implement required set of functions…

There are also many other runtime monads could be found on the internet.

In nutshell, you can run cache with whatever monad you want as long as you can implement all required functions for it, like `Concurrent[F]`,  `Parallel[F]`, `Runtime[F]`

**Comment by drobazko** [comment]
Thank you very much, Yaroslav!
Now it's clear!
